apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: letter
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s
  prune: true
  retryInterval: 3m0s
  sourceRef:
    kind: GitRepository
    name: letter-git
    namespace: flux-system
  targetNamespace: letter
  timeout: 3m0s
  wait: true
