apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - git-credentials.yaml
  - a50passos-git.yaml
  - a50passos-kustomization.yaml
  - a50passos-secrets.yaml
