apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - git-credentials.yaml
  - livinvicta-git.yaml
  - livinvicta-kustomization.yaml
  - livinvicta-secrets.yaml
