apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager/flux.yaml
  - external-dns/flux.yaml
  - local-path/flux.yaml
  - longhorn/flux.yaml
  - tailscale/flux.yaml
  - git-credentials.yaml
